import React,{useEffect,useMemo,useState}from"react";
import{Empty,Spin,message}from"antd";
import{CoffeeOutlined,DollarOutlined,ShopOutlined,ShoppingCartOutlined}from"@ant-design/icons";
import{Chart,Grid,Hero,Page,Panel,StatCard,Stats,TopList}from"./style";
import{API_URL}from"../../config";
const money=v=>`${Number(v||0).toLocaleString("vi-VN")} Ä‘`;
const shortMoney=v=>Number(v||0)>=1000000?`${(v/1000000).toFixed(1)}tr`:`${Math.round(v/1000)}k`;
const Dashboard=()=>{const[days,setDays]=useState(7);const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
useEffect(()=>{setLoading(true);fetch(`${API_URL}/admin/dashboard?days=${days}`,{headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}}).then(async r=>{if(!r.ok)throw new Error((await r.json()).message||"KhÃ´ng táº£i Ä‘Æ°á»£c dashboard");return r.json()}).then(setData).catch(e=>message.error(e.message)).finally(()=>setLoading(false))},[days]);
const max=useMemo(()=>Math.max(...(data?.revenueByDay||[]).map(i=>i.revenue),1),[data]);if(loading&&!data)return <div style={{display:"grid",placeItems:"center",minHeight:"65vh"}}><Spin size="large"/></div>;
return <Page><Hero><div><span className="eyebrow">Trung tÃ¢m váº­n hÃ nh</span><h1 className="title">Tá»•ng quan nhÃ  hÃ ng</h1><p className="sub">Theo dÃµi doanh thu, Ä‘Æ¡n hÃ ng vÃ  mÃ³n bÃ¡n cháº¡y trong má»™t mÃ n hÃ¬nh.</p></div><div className="period"><button className={days===7?"active":""} onClick={()=>setDays(7)}>7 ngÃ y</button><button className={days===30?"active":""} onClick={()=>setDays(30)}>30 ngÃ y</button></div></Hero><Stats>
<StatCard><div className="top"><span>Doanh thu hÃ´m nay</span><span className="icon"><DollarOutlined/></span></div><div><div className="value">{money(data?.todayRevenue)}</div><span className="hint">ÄÃ£ xÃ¡c nháº­n thanh toÃ¡n</span></div></StatCard>
<StatCard><div className="top"><span>ÄÆ¡n hÃ´m nay</span><span className="icon"><ShoppingCartOutlined/></span></div><div><div className="value">{data?.todayOrders||0}</div><span className="hint">HÃ³a Ä‘Æ¡n hoÃ n táº¥t</span></div></StatCard>
<StatCard><div className="top"><span>MÃ³n Ä‘Ã£ bÃ¡n</span><span className="icon"><CoffeeOutlined/></span></div><div><div className="value">{data?.todayDishes||0}</div><span className="hint">Tá»•ng sá»‘ lÆ°á»£ng mÃ³n</span></div></StatCard>
<StatCard><div className="top"><span>BÃ n hoáº¡t Ä‘á»™ng</span><span className="icon"><ShopOutlined/></span></div><div><div className="value">{data?.activeTables||0}</div><span className="hint">Äang order hoáº·c phá»¥c vá»¥</span></div></StatCard></Stats><Grid>
<Panel><div className="head"><div><h2>Doanh thu {days} ngÃ y</h2><span>Tá»•ng cá»™ng {money(data?.periodRevenue)}</span></div></div><Chart>{(data?.revenueByDay||[]).map(i=><div className="column" key={i.date}><span className="amount">{shortMoney(i.revenue)}</span><div className="track"><div className="bar" style={{height:`${Math.max(2,i.revenue/max*100)}%`}}/></div><span className="label">{new Date(`${i.date}T00:00:00`).toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</span></div>)}</Chart></Panel>
<Panel><div className="head"><div><h2>MÃ³n bÃ¡n cháº¡y</h2><span>Xáº¿p theo sá»‘ lÆ°á»£ng trong {days} ngÃ y</span></div></div>{data?.topDishes?.length?<TopList>{data.topDishes.map((i,n)=><div className="item" key={i.dishName}><span className="rank">{n+1}</span><div><span className="name">{i.dishName}</span><span className="revenue">{money(i.revenue)}</span></div><span className="qty">{i.quantity} mÃ³n</span></div>)}</TopList>:<Empty description="ChÆ°a cÃ³ dá»¯ liá»‡u bÃ¡n hÃ ng"/>}</Panel></Grid></Page>};export default Dashboard;
