import React,{useEffect,useMemo,useState}from"react";
import{Empty,Spin,message}from"antd";
import{CoffeeOutlined,DollarOutlined,ShopOutlined,ShoppingCartOutlined}from"@ant-design/icons";
import{Chart,Grid,Hero,Page,Panel,StatCard,Stats,TopList}from"./style";
const money=v=>`${Number(v||0).toLocaleString("vi-VN")} đ`;
const shortMoney=v=>Number(v||0)>=1000000?`${(v/1000000).toFixed(1)}tr`:`${Math.round(v/1000)}k`;
const Dashboard=()=>{const[days,setDays]=useState(7);const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
useEffect(()=>{setLoading(true);fetch(`http://localhost:8080/admin/dashboard?days=${days}`,{headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}}).then(async r=>{if(!r.ok)throw new Error((await r.json()).message||"Không tải được dashboard");return r.json()}).then(setData).catch(e=>message.error(e.message)).finally(()=>setLoading(false))},[days]);
const max=useMemo(()=>Math.max(...(data?.revenueByDay||[]).map(i=>i.revenue),1),[data]);if(loading&&!data)return <div style={{display:"grid",placeItems:"center",minHeight:"65vh"}}><Spin size="large"/></div>;
return <Page><Hero><div><span className="eyebrow">Trung tâm vận hành</span><h1 className="title">Tổng quan nhà hàng</h1><p className="sub">Theo dõi doanh thu, đơn hàng và món bán chạy trong một màn hình.</p></div><div className="period"><button className={days===7?"active":""} onClick={()=>setDays(7)}>7 ngày</button><button className={days===30?"active":""} onClick={()=>setDays(30)}>30 ngày</button></div></Hero><Stats>
<StatCard><div className="top"><span>Doanh thu hôm nay</span><span className="icon"><DollarOutlined/></span></div><div><div className="value">{money(data?.todayRevenue)}</div><span className="hint">Đã xác nhận thanh toán</span></div></StatCard>
<StatCard><div className="top"><span>Đơn hôm nay</span><span className="icon"><ShoppingCartOutlined/></span></div><div><div className="value">{data?.todayOrders||0}</div><span className="hint">Hóa đơn hoàn tất</span></div></StatCard>
<StatCard><div className="top"><span>Món đã bán</span><span className="icon"><CoffeeOutlined/></span></div><div><div className="value">{data?.todayDishes||0}</div><span className="hint">Tổng số lượng món</span></div></StatCard>
<StatCard><div className="top"><span>Bàn hoạt động</span><span className="icon"><ShopOutlined/></span></div><div><div className="value">{data?.activeTables||0}</div><span className="hint">Đang order hoặc phục vụ</span></div></StatCard></Stats><Grid>
<Panel><div className="head"><div><h2>Doanh thu {days} ngày</h2><span>Tổng cộng {money(data?.periodRevenue)}</span></div></div><Chart>{(data?.revenueByDay||[]).map(i=><div className="column" key={i.date}><span className="amount">{shortMoney(i.revenue)}</span><div className="track"><div className="bar" style={{height:`${Math.max(2,i.revenue/max*100)}%`}}/></div><span className="label">{new Date(`${i.date}T00:00:00`).toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</span></div>)}</Chart></Panel>
<Panel><div className="head"><div><h2>Món bán chạy</h2><span>Xếp theo số lượng trong {days} ngày</span></div></div>{data?.topDishes?.length?<TopList>{data.topDishes.map((i,n)=><div className="item" key={i.dishName}><span className="rank">{n+1}</span><div><span className="name">{i.dishName}</span><span className="revenue">{money(i.revenue)}</span></div><span className="qty">{i.quantity} món</span></div>)}</TopList>:<Empty description="Chưa có dữ liệu bán hàng"/>}</Panel></Grid></Page>};export default Dashboard;
