services:
  - type: web
    name: menuorder-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://menuorder-1.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
